import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { authApi, orderApi, userApi } from "../services/api";
import { openRazorpayCheckout } from "../utils/razorpayCheckout";
import toast from "react-hot-toast";
import { Pencil, Trash2, Plus } from "lucide-react";

/* ---------- helpers ---------- */
const sortAddresses = (addresses, defaultId) => [
  ...addresses.filter((a) => a._id === defaultId),
  ...addresses.filter((a) => a._id !== defaultId),
];

const emptyForm = {
  fullName: "",
  phone: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  pincode: "",
};

function Checkout({ cartItems, setCartItems }) {
  const navigate = useNavigate();

  const [addresses, setAddresses] = useState([]);
  const [defaultAddressId, setDefaultAddressId] = useState(null);
  const [selectedAddressId, setSelectedAddressId] = useState(null);
  const [form, setForm] = useState(null);

  const [submitting, setSubmitting] = useState(false);
  const [paying, setPaying] = useState(false);

  const totalAmount = cartItems.reduce(
    (sum, item) => sum + item.price * item.quantity,
    0
  );

  /* ================= Load user ================= */
  const loadUser = async () => {
    const res = await authApi.me();
    const u = res.data.user;

    const list = u.addresses || [];
    setAddresses(list);
    setDefaultAddressId(u.defaultAddress || null);
    setSelectedAddressId(u.defaultAddress || list[0]?._id || null);
  };

  useEffect(() => {
    loadUser().catch(() => {
      toast.error("Please login to continue");
      navigate("/login");
    });
  }, [navigate]);

  /* ================= Persist addresses ================= */
  const persistAddresses = async (updated, newDefault = defaultAddressId) => {
    await userApi.updateProfile({
      addresses: updated,
      defaultAddress: newDefault,
    });

    await loadUser();
  };

  /* ================= Address actions ================= */
  const handleDelete = async (id) => {
    const updated = addresses.filter((a) => a._id !== id);

    let newDefault = defaultAddressId;
    if (id === defaultAddressId) {
      newDefault = updated[0]?._id || null;
    }

    await persistAddresses(updated, newDefault);
    toast.success("Address deleted");
  };

  const handleSaveAddress = async () => {
    const required = [
      "fullName",
      "phone",
      "addressLine1",
      "city",
      "state",
      "pincode",
    ];

    for (const f of required) {
      if (!form[f]) {
        toast.error("Fill all required fields");
        return;
      }
    }

    let updated;

    if (form._id) {
      // edit
      updated = addresses.map((a) =>
        a._id === form._id ? { ...a, ...form } : a
      );
    } else {
      // add – KEEP _id GENERATED BY MONGO
      updated = [...addresses, form];
    }

    await persistAddresses(updated);
    setForm(null);
    toast.success("Address saved");
  };

  /* ================= Place order ================= */
  const handlePlaceOrder = async () => {
    const address = addresses.find((a) => a._id === selectedAddressId);

    if (!address) {
      toast.error("Please select a delivery address");
      return;
    }

    try {
      setSubmitting(true);
      console.log("PLACING ORDER", {
        selectedAddressId,
        cartItems,
        totalAmount,
      });

      const res = await orderApi.create({
        addressId: selectedAddressId, // ✅ REQUIRED
        orderItems: cartItems.map((item) => ({
          product: item._id || item.id,
          name: item.name,
          price: item.price,
          quantity: item.quantity,
        })),
        paymentMethod: "RAZORPAY",
        totalAmount,
      });

      const orderId = res.data.order._id;

      setPaying(true);

      await openRazorpayCheckout({
        orderId,
        onSuccess: () => {
          setPaying(false);
          navigate("/order-success", {
            state: { orderId, totalAmount },
          });
          setTimeout(() => setCartItems([]), 0);
        },
        onFailure: () => {
          setPaying(false);
          toast.error("Payment failed");
        },
      });
    } catch (err) {
      console.error(err);
      toast.error("Unable to place order");
    } finally {
      setSubmitting(false);
    }
  };

  /* ================= Empty cart ================= */
  if (!cartItems.length) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center">
        <h2 className="mb-4 text-xl font-semibold">Your cart is empty</h2>
        <Link to="/" className="text-green-700 font-medium">
          Continue Shopping
        </Link>
      </div>
    );
  }

  const disabled = submitting || paying;
  const sorted = sortAddresses(addresses, defaultAddressId);

  return (
    <div className="min-h-screen bg-[#fdf9f3]">
      <div className="max-w-5xl mx-auto px-4 py-16">
        <h1 className="mb-10 text-3xl font-serif font-bold">Checkout</h1>

        {/* Cart */}
        <div className="mb-8 rounded bg-white p-6 shadow">
          {cartItems.map((item) => (
            <div
              key={item._id || item.id}
              className="flex justify-between py-2"
            >
              <span>
                {item.name} × {item.quantity}
              </span>
              <span className="font-semibold">
                ₹{item.price * item.quantity}
              </span>
            </div>
          ))}
        </div>

        {/* Addresses */}
        <div className="mb-8 rounded bg-white p-6 shadow">
          <div className="flex justify-between mb-4">
            <h2 className="font-semibold">Delivery Address</h2>
            <button
              onClick={() => setForm(emptyForm)}
              className="flex items-center gap-1 text-sm text-green-700"
            >
              <Plus size={16} /> Add
            </button>
          </div>

          {sorted.map((addr) => (
            <div
              key={addr._id}
              onClick={() => setSelectedAddressId(addr._id)}
              className={`mb-3 cursor-pointer rounded border p-3 ${
                selectedAddressId === addr._id
                  ? "border-green-700 bg-green-50"
                  : "border-gray-300"
              }`}
            >
              <div className="flex justify-between">
                <div>
                  <p className="font-medium">
                    {addr.fullName}
                    {addr._id === defaultAddressId && (
                      <span className="ml-2 text-xs bg-green-100 text-green-800 px-2 rounded">
                        DEFAULT
                      </span>
                    )}
                  </p>
                  <p className="text-sm">
                    {addr.addressLine1}
                    {addr.addressLine2 && `, ${addr.addressLine2}`}
                  </p>
                  <p className="text-sm">
                    {addr.city}, {addr.state} - {addr.pincode}
                  </p>
                  <p className="text-sm">{addr.phone}</p>
                </div>

                <div className="flex gap-3">
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      setForm(addr);
                    }}
                  >
                    <Pencil size={16} className="text-gray-600 hover:text-gray-800" />
                  </button>
                  <button
                    onClick={(e) => {
                      e.stopPropagation();
                      handleDelete(addr._id);
                    }}
                  >
                    <Trash2 size={16} className="text-red-600 hover:text-red-700" />
                  </button>
                </div>
              </div>
            </div>
          ))}

          {form && (
            <div className="border-t pt-4 space-y-2">
              {Object.keys(emptyForm).map((f) => (
                <input
                  key={f}
                  placeholder={f}
                  value={form[f] || ""}
                  onChange={(e) => setForm({ ...form, [f]: e.target.value })}
                  className="w-full border p-2 rounded"
                />
              ))}
              <button
                onClick={handleSaveAddress}
                className="bg-green-700 text-white px-4 py-2 rounded"
              >
                Save Address
              </button>
            </div>
          )}
        </div>

        {/* Total */}
        <div className="flex justify-between bg-[#f5efe6] p-6 rounded">
          <span className="font-semibold">Total</span>
          <span className="font-bold text-green-800">₹{totalAmount}</span>
        </div>

        {/* Pay */}
        <button
          disabled={disabled}
          onClick={handlePlaceOrder}
          className={`mt-8 w-full py-4 rounded font-semibold ${
            disabled
              ? "bg-gray-300 text-gray-500"
              : "bg-green-700 text-white hover:bg-green-800"
          }`}
        >
          {paying
            ? "Processing payment..."
            : submitting
            ? "Placing order..."
            : "Pay & Place Order"}
        </button>
      </div>
    </div>
  );
}

export default Checkout;
